### ISSUE TITLE
اضافه کردن ترجمه‌ی فارسی برای کلید واژه‌های الگوریتم

### ISSUE THREAD

**Issue by amirhakh** [sinamomken/tehran-thesis#10]
سلام
وقت شما بخیر
خیلی ممنون از پروژه ای که آماده کرده اید.

یک درخواست داشتم.
این موارد را به قسمت commands اضافه کنید

```LaTeX
\renewcommand{\algorithmicfor}{\textbf{برای}}
\renewcommand{\algorithmicto}{\textbf{تا}}
%\renewcommand{\algorithmicstep}{\textbf{گام}}
\renewcommand{\algorithmicendfor}{\textbf{پایان حلقه‌ی برای}}
\renewcommand{\algorithmicdo}{\textbf{انجام بده:}}
\renewcommand{\algorithmicwhile}{\textbf{تا زمانی که}}
\renewcommand{\algorithmicendwhile}{\textbf{پایان حلقه‌ی شرطی}}
\renewcommand{\algorithmicif}{\textbf{اگر}}
\renewcommand{\algorithmicthen}{\textbf{آنگاه:}}
\renewcommand{\algorithmicelse}{\textbf{در غیر این صورت:}}
\renewcommand{\algorithmicelsif}{\textbf{در غیر این صورت اگر}}
\renewcommand{\algorithmicendif}{\textbf{پایان شرط}}
\renewcommand{\algorithmicrepeat}{\textbf{تکرار کن:}}
\renewcommand{\algorithmicuntil}{\textbf{تا زمانی که}}
\renewcommand{\algorithmicloop}{\textbf{تکرار کن:}}
\renewcommand{\algorithmicendloop}{\textbf{پایان حلقه‌ی تکرار}}
\renewcommand{\algorithmicreturn}{\textbf{بازگشت}}
\renewcommand{\algorithmiccomment}{\textbf{توضیح:}}
```

**Comment by hadisfr** [comment]
سلام
‫فرصت دارید خودتون برای این مرج ریکوئست بزنید و علاوه بر اضافه کردن این‌ها، به نمونهٔ  الگوریتم موجود توی کد هم چند مورد از این‌ها رو اضافه کنید؟

**Comment by sinamomken** [comment]
سلام
تشکر بابت پیشنهاد شما برای بهبود پروژه.

با این حال من تا حالا شبه‌کد الگوریتمی با زبان فارسی ندیدم. حتی در کتاب‌های فارسی هم الگوریتم را معمولا به زبان انگلیسی می‌نویسند چون نام متغیرها هم انگلیسی است.

به طور کلی نظر مثبتی پیرامون اضافه کردن کلیدواژه‌های فارسی به الگوریتم ندارم، مگر آنکه کلیدواژه‌های لاتین الگوریتم همچنان حفظ شوند و کلیدواژه های فارسی علاوه بر کلیدواژه‌های لاتین اضافه گردند.

نکات هادی را نیز جهت ایجاد مرج ریکوئست و آوردن نمونه از الگوریتم فارسی در راهنمای این قالب مد نظر قرار دهید.

**Comment by amirhakh** [comment]
سلام
بله. حتما یک نسخه آماده می‌کنم
البته ممکن است بر روی ترجمه‌ها اختلاف نظر باشد. ولی سعی کردم که ترجمه‌های خوبی انتخاب بشود

الگوریتم فارسی هم شاید سلیقه ای باشه. ولی برای متن فارسی به نظرم بهتره که باشه. باز هم به اختیار خود دانشجو هست. من که برای تز خودم هم فارسی دارم و هم انگلیسی.

**Comment by hadisfr** [comment]
<div dir="rtl">
من می‌خواستم یه ریلیز جدید بزنم با توجه به تغییرات این چند وقت. پس صبر می‌کنم.

در مورد ترجمه‌ها هم اگر تمایل داشتید می‌تونیم قبلش صحبت کنیم یا ول ریکوئست بذارید همون‌جا صحبت کنیم.
</div>

**Comment by amirhakh** [comment]
سلام
این نمونه الگوریتمی هست که خودم نوشتم

```latex
\begin{algorithm}[ht]
	\onehalfspacing
	\caption{الگوریتم اجرای برنامه‌ی شبیه سازی} \label{alg:simulation-random}
	\begin{algorithmic}[1]
		\REQUIRE زمان t به عنوان زمان لازم برای انجام شبیه سازی،\\
		\REQUIRE نوع گراف شبکه برای شبیه سازی،
		\ENSURE جدول تغییرات گراف از لحظه‌ی ۰ تا t.
		\STATE بارگیری گراف و یا ساخت یک گراف تصادفی.
		\FOR {تمام لحاظات در بازه‌ی ۰ تا t}
		\STATE برای تمام ارتباط‌ها وضعیت انتشار بیماری و میزان انتقال دانش (یادگیری/فراموشی) حساب شود.
		\STATE برای تمام گره‌ها وضعیت بیمار شدن و میزان دانش (یادگیری/فراموشی)  حساب شود.
		\STATE وضعیت تمام گره‌ها به روز شود.
		\ENDFOR
	\end{algorithmic}
\end{algorithm}
```

![image](https://user-images.githubusercontent.com/2285342/96571147-133e0680-12d8-11eb-9fb8-522c6b4163a6.png)

اگر نظری دارید بفرمایید
اگر موافق هستید که یک pull request‌  بفرستم

**Comment by hadisfr** [comment]
<div dir="rtl">
من با کلیتش موافقم. ••پایان حلقه‌ی برای•• یه کم برام عجیبه فقط، ولی راه حلی هم ندارم.

آقای ممکن نظر بدن ببینیم چه کنیم. @sinamomken 
</div>

**Comment by amirhakh** [comment]
<div dir=rtl>
حقیقت اش من اول برای همه پایان یا اتمام حلقه گذاشته بودم. اما دیدم که syntax‌ خودش اینه که if .... then .... end if هست.
برای همه هم به همین شکل بود.
انگلیسی اش هم end for و یا مشابه این را داره.
چون راه حلی به ذهن ام نرسید، همین شکل گذاشتم.
از یک جهت هم خوبه، چون اگر چند حلقه‌ی تو در تو داشته باشه، مشخص می‌شه که کجا پایان چه قسمتی هست.
</div>

**Comment by hadisfr** [comment]
‫خب آقای ممکن هم با کلیت ماجرا موافقن. می‌خواید pull requestش رو بذارید یه مثال فارسی هم اضافه کنید براش.  🤔

**Comment by amirhakh** [comment]
سلام. یک درخواست دادم.
