### ISSUE TITLE
اعداد فارسی در نوشتن معادلات

### ISSUE THREAD

**Issue by amirhakh** [sinamomken/tehran-thesis#13]
سلام

وقت شما بخیر

یک نکته ای در رابطه با فرمول‌ها وجود داره.
اگر در وسط متن فارسی یک فرمول بنویسیم، اعداد آن فارسی هستند و باقی مطالب انگلیسی.
در داخل فرمول نمی‌شه از `\begin{latin}` استفاده کرد و حتما باید قبل و بعد از فرمول از این دستور استفاده کرد.
در حالت عادی، شماره‌ی فرمول فارسی نوشته می‌شه.

اما اگر دو طرف اش از دستور `latin‍` استفاده کنیم، شماره‌ی فرمول به شکل انگلیسی نوشته می‌شه که جالب نیست. ولی مشکل اعداد فارسی در فرمول حل می‌شه.

برای این مسئله راه حلی وجود دارد.

**Comment by hadisfr** [comment]
<div dir="rtl">

سلام
برای تغییر فارسی و انگلیسی بودن اعداد درون فرمول‌ها از بعضی آپشن‌های `xepersian` می‌شه استفاده کرد که بسته به نسخهٔ بسته ممکنه تغییر کنن.
<div dir="ltr">

```tex
\usepackage[
    inlinemathdigits=persian,
    displaymathdigits=default
]{xepersian}
```
</div> 

اگر `setmathdigitfont` رو حذف کنین هم به طور پیش‌فرض اعداد فرمول‌ها انگیسی می‌شه فکر کنم.
</div>

**Comment by amirhakh** [comment]
بله
درست می‌فرمایید
دیدم و این تغییر را در متن دادم
خیلی خیلی ممنون
