### ISSUE TITLE
مشکل برچسب زنی برای \subfloat

### ISSUE THREAD

**Issue by amirhakh** [sinamomken/tehran-thesis#14]
<div dir=rtl>

سلام
وقت شما بخیر

یک مشکلی برای ارجاع به \subfloat وجود دارد که از توان بنده خارج بود.
گفتم که اگر برای شما مسئله‌ی ساده ای است، شما زحمت اصلاح اش را بکشید.

مشکل در ارجاع به یک subfloat است. در این حالت بهتر است که یک «.» بین حرف و شماره شکل قرار بگیرد.

نمونه کد بنده

</div>

```latex
	\subfloat[AU]{
		\label{fig:Alerting-seperate}
		\begin{tikzpicture}[thick,scale=1.6, every node/.style={scale=1.2}]
			\node[state] (u) at (0,1 ) {U};
			\node[state] (a) at (0,-1) {A};
			
			\draw[->] (u) edge[bend left, below] node [anchor=east] {$\kappa$} (a);
			\draw[->] (a) edge[bend left, above] node [anchor=west] {$\omega$} (u);
		\end{tikzpicture}
	}
\caption{نمودارهای مدل‌های پایه‌ای}
	\label{fig:single-and-combination}
```

<div dir=rtl>

![image](https://user-images.githubusercontent.com/2285342/97270014-a5e42580-1843-11eb-9214-dcfea6942209.png)

متن ارجاع به زیر شکل بالا

![image](https://user-images.githubusercontent.com/2285342/97270031-b09eba80-1843-11eb-862d-094143d24e1b.png)

از قالب خوب تون هم خیلی راضی ام

دست شما درد نکنه

</div>

**Comment by hadisfr** [comment]
سلام

‫این رو یه تست بکنین، فکر می‌کنم مسأله رو حل بکنه. احتمالاً اگه به اواخر فایل `tex/commands.tex` اضافه‌ش کنین جواب بده.

```tex
\makeatletter
\renewcommand{\p@subfigure}{\thefigure.}
\makeatother
```

‫من الان فرصت ندارم روی خود تمپلیت تستش کنم متأسفانه. رو یه فایل کوچیک تست کردم:

```tex
\documentclass{article}

\usepackage{subfig}
\usepackage{graphicx}
\usepackage[colorlinks]{hyperref}
\usepackage{xepersian}
\settextfont{Yas}

\makeatletter
\renewcommand{\p@subfigure}{\thefigure.}
\makeatother

\begin{document}

\begin{figure}
    \subfloat[سیمرغ]{
        \label{fig:sub-a}
        \includegraphics[width=0.48\textwidth]{1024px-Senmurv.svg.png}
    }
    \qquad
    \subfloat[سیمرغ]{
        \label{fig:sub-b}
        \includegraphics[width=0.48\textwidth]{1024px-Senmurv.svg.png}
    }
\caption{نمادها}
    \label{fig:total}
\end{figure}

\noindent
در \autoref{fig:total} چند نماد مثل سیمرغ \subref{fig:sub-a} دیده می‌شود.
شکل~\ref{fig:sub-a} نیز یک سیمرغ را نشان می‌دهد.

\end{document}
```
![image](https://user-images.githubusercontent.com/24562441/97375043-07050b00-18cf-11eb-90de-51f3c650e2ec.png)

‫جدای از این‌ها شخصاً این حالت به نظرم زیباتره ولی توی تمپلیت احتمالاً باید استاندارد رو حفظ کنیم. [مستندات](https://github.com/sinamomken/tehran-thesis/wiki/%D9%85%D8%B3%D8%AA%D9%86%D8%AF%D8%A7%D8%AA-%D9%86%DA%AF%D8%A7%D8%B1%D8%B4-%D9%BE%D8%A7%DB%8C%D8%A7%D9%86%E2%80%8C%D9%86%D8%A7%D9%85%D9%87-%D8%AF%D8%B1-%D9%BE%D8%B1%D8%AF%DB%8C%D8%B3-%D8%AF%D8%A7%D9%86%D8%B4%DA%A9%D8%AF%D9%87%E2%80%8C%D9%87%D8%A7%DB%8C-%D9%81%D9%86%DB%8C-%D8%AF%D8%A7%D9%86%D8%B4%DA%AF%D8%A7%D9%87-%D8%AA%D9%87%D8%B1%D8%A7%D9%86) دانشگاه مثال یا توضیحی داره در مورد این قضیه؟

**Comment by amirhakh** [comment]
سلام
خیلی ممنون
درست شد
