### ISSUE TITLE
Please change License

### ISSUE THREAD

**Issue by ssinad** [sinamomken/tehran-thesis#2]
I suggest the license to be changed into something else such as [LPPL](https://www.latex-project.org/lppl/)

**Comment by sinamomken** [comment]
Hmmm,
I am not expert in legal and license issues.
For this template to become completely standard, it should be confirmed by authorities of University of Tehran, therefor I should ask their opinion about the license too. However, the license must remain an open one, fully compliant with licenses of previous projects used here.
Temporarily, I have chosen GPLv3, as an open and permissive license, therefor others can freely use, change and distribute this template.
