### ISSUE TITLE
\newacronym representation problem with Persian long-form

### ISSUE THREAD

**Issue by ali-shamakhi** [sinamomken/tehran-thesis#21]
Using an acronym containing Persian long-form text does not render correctly.

Example:
- Definition: [`\newacronym{F}{$F$}{نیرو (N)}`](https://github.com/sinamomken/tehran-thesis/blob/9d32e367feb2d6c2cff5a5829a248ca1c230616b/tex/acronyms.tex#L2)
- Usage: [`\gls{F}`](https://github.com/sinamomken/tehran-thesis/blob/9d32e367feb2d6c2cff5a5829a248ca1c230616b/tex/appendix3.tex#L335)
- Rendered:
![image](https://user-images.githubusercontent.com/10486368/121400776-3a337080-c96d-11eb-8b08-94582c901790.png)

The issue is present at page 46 (73 / 84) of [the latest PDF release](https://github.com/sinamomken/tehran-thesis/releases/download/20.10/main.pdf).

**Comment by hadisfr** [comment]
با این تغییر اصل مشکل حل شد. (تک‌لایو ۲۰۲۲) فقط الان هنوز شمارهٔ فوت‌نوت انگلیسی می‌خوره که راه‌حلی براش ندارم.
![image](https://user-images.githubusercontent.com/24562441/177398870-53ac530e-9ba2-47da-9d71-95328c9bf963.png)
