### ISSUE TITLE
مشکل در ایجاد واژه نامه

### ISSUE THREAD

**Issue by mahdavian74** [sinamomken/tehran-thesis#22]
با عرض سلام و ارادت
من از قالب شما برای نوشتن پایان نامه استفاده میکنم ولب الان مشکل با ایجاد واژه نامه دارم

[حل مشکل واژه نامه](http://qa.parsilatex.com/16166/%D9%85%D8%B4%DA%A9%D9%84-%D8%AF%D8%B1-%D8%A7%DB%8C%D8%AC%D8%A7%D8%AF-%D9%88%D8%A7%DA%98%D9%87-%D9%86%D8%A7%D9%85%D9%87-%D8%A8%D8%A7-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D8%A8%D8%B3%D8%AA%D9%87-glossaries)
 را مطالعه کردم و تمام موارد را به تایپ تت ها اضافه کردم ولی هنوز در اجرای ران با مشکل مواجه میشوم و ارور زیر را نمایش می‌دهد.

Unsupported input markup xindy .

usage: xindy.pl [-V?h] [-qv] [-d magic] [-o outfile.ind] [-t log] \
            [-L lang] [-C codepage] [-M module] [-I input] \
            [--interactive] [--mem-file xindy.mem] \
	    [idx0 idx1 ...]

GNU-STYLE LONG OPTIONS FOR SHORT OPTIONS:

 -V / --version
 -? / -h / --help
 -q / --quiet
 -v / --verbose
 -d / --debug          (multiple times)
                       (supported: script, keep_tmpfiles, markup, level=n)
 -o / --out-file
 -t / --log-file
 -L / --language
 -C / --codepage
 -M / --module         (multiple times)
 -I / --input-markup   (supported: latex, xelatex, omega, xindy)

**Comment by hadisfr** [comment]
بر اساس این یک خط لاگ حدسی نمی‌تونم بزنم. (خطوط بعدی صرفاً راهنمای xindy اند.) اگه لاگ کامل اجرا بود شاید می‌شد چیزی گفت.

به هر حال الان با نسخهٔ تک‌لایو ۲۰۲۲ به نظر هم اسکریپت بیلد و هم latexmk کار می‌کنه. اگر کاربر لینوکس هستید هم حتماً تک‌لایو ۲۰۲۲ رو از سایت خودش دانلود کنید و دوباره امتحان کنید. بسته‌های موجود روی ریپوهای اوبونتو و… با هم ناسازگارند.
