### ISSUE TITLE
مشکل در اجرای واژه نامه

### ISSUE THREAD

**Issue by rezakarbasi** [sinamomken/tehran-thesis#23]
باسلام و تشکر از قالب خوبتون

من از ویرایشگر texpad استفاده میکنم. این ادیتور در اجراش از همون فایل build که نوشته اید استفاده میکنه ولی در انتها واژه نامه درست نمیشود و خطای زیر را می‌دهد:

main.ind (line 1)
Undefined control sequence. (...ytoctitle]{\glossarytitle}\glossarypreamble ...)

اگر که کار خاصی باید میکردم که نکردم بفرمایید. ممنون

**Comment by hadisfr** [comment]
بر اساس این یک خط لاگ حدسی نمی‌تونم بزنم. اگه لاگ کامل اجرا بود شاید می‌شد چیزی گفت.

به هر حال الان با نسخهٔ تک‌لایو ۲۰۲۲ به نظر هم اسکریپت بیلد و هم latexmk کار می‌کنه. اگر کاربر لینوکس هستید هم حتماً تک‌لایو ۲۰۲۲ رو از سایت خودش دانلود کنید و دوباره امتحان کنید. بسته‌های موجود روی ریپوهای اوبونتو و… با هم ناسازگارند.
