### ISSUE TITLE
xepersian_mathsdigitspec_primitive_font_char_if_exist Error

### ISSUE THREAD

**Issue by bshramin** [sinamomken/tehran-thesis#25]
While compiling the project, I ran into [this error](http://qa.parsilatex.com/35710/__xepersian_mathsdigitspec_primitive_font_char_if_exist), which I fixed in [this commit](https://github.com/bshramin/cappu-thesis/commit/c6bb5f5958f2bd630aec46ed45b094c596a759db).
If the issue and the solution seem reasonable, I can create a pull request to this repository.

**Comment by hadisfr** [comment]
‫مشکل مربوط به بستهٔ زی‌پرشن بوده. https://github.com/persiantex/xepersian/issues/17

در تک‌لایو ۲۰۲۲ هم به نظر مشکل رفع شده. (ر.ک. https://github.com/tex-persian/xepersian/discussions/1) بنابراین به نظر میاد دیگه نیازی به هات‌فیکس‌های قدیمی نباشه.
