### ISSUE TITLE
خطای دستور setiranicfont

### ISSUE THREAD

**Issue by hadiasheri** [sinamomken/tehran-thesis#27]
با سلام،
من روی اوبونتو ۱۸.۰۴ با تک لایو ۲۰۲۱ وقتی که قالب را کامپایل می‌کنم با خطاهای مرتبط با زی‌پرشین برخورد می‌کنم.
مثلا این خطا:
Undefined control sequence \setiranicfont

ممنون می‌شوم راهنمایی بفرمایید که چطور این مشکل را برطرف کنم.

**Comment by hadisfr** [comment]
سلام
حدس می‌زنم مشکلتون مشابه https://github.com/sinamomken/tehran-thesis/issues/9 باشه و همون راه‌حل‌ها هم جواب بده. لاگ کامل رو بنویسید.

کلاً زی‌پرشن روی تک‌لایو ۲۰۲۱ مشکلاتی داره و اذیت خواهید شد. من اکیداً پیشنهاد می‌کنم مهاجرت کنید به تک‌لایو ۲۰۲۲.

**Comment by hadiasheri** [comment]
با نصب تک‌لایو نسخه ۲۰۲۲ مشکل برطرف شد.
 ممنون
