### ISSUE TITLE
عدم امکان قرار دادن حروف یونانی در فهرست اختصارات

### ISSUE THREAD

**Issue by eafshari** [sinamomken/tehran-thesis#29]
با سلام،
من از آخرین ورژن تمپلیتی که قرار دادین استفاده کردم. موقع وارد کردن فهرست اختصارات، امکان تعریف علائم یونانی وجود نداره. امکانش هست که فهرست اختصارات به شکل گروه بندی شده (حروفی که بالای علائم نوشته میشه) نباشه؟ چجوری میتونم کاری کنم تا حروف یونانی هم وارد فهرست اختصارات کنم؟

**Comment by hadisfr** [comment]
سلام
لطفاً یک مثال قرار بدید از کد مورد نظرتون برای درج علامت اختصاری و خروجی صفحهٔ فهرست اختصارات و مشخص کنید انتظار دارید خروجی درست چطوری باشه که بتونم شرایط رو بازسازی کنم، من در صورت امکان بررسی می‌کنم ببینم راهی پیدا می‌کنم یا نه.

**Comment by eafshari** [comment]
سلام مجدد،
\newacronym{H}{$\alpha$}{\rl{زاویه جریان}}
در این مثال حرف یونانی آلفا میخوام به عنوان حرف اختصاری توی لیست اختصارات چاپ بشه ولی از انجایی که فهرست اختصارات بر اساس فقط حروف انگلیسی دسته بندی شده، نماد آلفا رو شامل نمیشه و فهرست اختصارات کلا میپره. طبق پایان نامه هایی که دیدم، فهرست اختصاراتشون به این صورت هست که در ابتدا حروف انگلیسی به ترتیب ظاهر میشن (البته مثل این تمپلیت هر حرف توی دسته بندی جدا قرار نمیگیره، صرفا بر اساس الفبا مرتب میشن) و بعد از اون یک لیستی تحت عنوان لیست نمادهای یونانی میاد، و در نهایت لیست زیرنویس ها. همشون تحت عنوان فهرست اختصارات هستند ولی زیربخش های لیست نمادهای یونانی و لیست زیرنویس ها رو هم دارند.

**Comment by eafshari** [comment]
با سلام،
یک مشکل دیگه هم در مورد فهرست اختصارات دارم و اونم این هست که یک نماد رو داخل متن معرفی کردم، و دیگه لازم ندارم در پایین صفحه بصورت پی نوشت معنی اون کلمه بیاد دوباره. مثلا متنی بصورت زیر دارم:
"در رابطه بالا L طول مشخصه جریان می باشد." نمیخوام برای پارامتر L پایین صفحه دوباره بنویسه طول مشخصه، ولی از طرفی میخوام که پارامتر L در فهرست اختصارات همراه با معنیش چاپ بشه. راهی برای این مورد هست؟

**Comment by hadisfr** [comment]
این مورد دوم تا جایی که می‌دونم خلاف قواعده. ولی مثلاً با `\glsunset` شاید بتونید یه کارایی بکنید. [این‌جا](https://en.wikibooks.org/wiki/LaTeX/Glossary#Referring_acronyms) رو ببینید.

**Comment by hadisfr** [comment]
برای مورد اول هم این پارامتر sort شاید به درد بخوره. [این‌جا](https://tex.stackexchange.com/a/571824) رو ببینید مثلاً.
