### ISSUE TITLE
داشتن دو استاد داور

### ISSUE THREAD

**Issue by mostafav68** [sinamomken/tehran-thesis#30]
باسلام
من دوتا داور داخلی و دو داور خارجی دارم اما این تمپلیت امکان ثبت یک داور داخلی و یک داور خارجی رو میده چجوری میشه داور دوم داخلی و داور دوم خارجی رو اضافه کنم؟
همچنین مشاور رو میزنه از دانشگاه خودم چجوری میشه دانشگاه استاد مشاور رو عوض کنم

**Comment by hadisfr** [comment]
جدول مشخصات داوران این‌جا توی فایل cls ذکر شده که باید مطابق نیازتون ویرایشش کنید:

https://github.com/sinamomken/tehran-thesis/blob/79669850db960b307cc26d0e9cfb57236fa898af/tex/tehran-thesis.cls#L365-L402

اگر فرصت کنم باید برای حالت رسالهٔ دکتری امکان تعریف راحت‌تر دو داور داخلی و دو داور خارجی در فایل [faTitle.tex](https://github.com/sinamomken/tehran-thesis/blob/79669850db960b307cc26d0e9cfb57236fa898af/tex/faTitle.tex) رو هم اضافه کنم ولی فعلاً بعیده برسم به این کارها.
