### ISSUE TITLE
ترتیب مراجع

### ISSUE THREAD

**Issue by mostafav68** [sinamomken/tehran-thesis#31]
سلام توی این تمپلیت من پایان نامه رو نوشتم و مراجع به ترتیب حروف الفبا هستند چجوری میشه ترتیب مراجع رو عوض کرد و به ترتیب قرارگیری توی متن گذاشت؟ الان مثلا فصل اولم اولین مرجع شماره 18 دومین مرجع شماره 67 و همینطور الی آخر می خوام به ترتیب وارد شدن مراجع در متن در قسمت مراجع قرار بگیرند

**Comment by hadisfr** [comment]
استایل کتاب‌نامه توی این خط تعریف شده:
https://github.com/sinamomken/tehran-thesis/blob/79669850db960b307cc26d0e9cfb57236fa898af/main.tex#L63
می‌تونید به جای plain-fa از استایل‌هایی مثل unsrt-fa یا ieeetr-fa استفاده کنید که مراجع رو به ترتیب استفاده میارن. اطلاعات بیشتر در مورد استایل‌ها [این‌جا](http://mirrors.ctan.org/biblio/bibtex/contrib/persian-bib/Persian-bib-userguide.pdf) در دسترسه.
