### ISSUE TITLE
تغییر نام تصاویر و جداول در فهرست مطالب

### ISSUE THREAD

**Issue by bexxnaz** [sinamomken/tehran-thesis#32]
سلام، به چه صورت نام تصاویر و جداول را در فهرست مطالب تغییر بدهیم؟
  و سوال دوم اینکه وقتی از رفرنس در کپشن تصاویر استفاده می‌شود و فهرست تصاویر اولین صفحات قرار دارد، ترتیب عددی رفرنسا براساس متن اصلی نیست. شماره رفرنس تصاویر از یک شروع میشه. اینو به چه صورت  میشه درست کرد؟

ممنون.

**Comment by hadisfr** [comment]
سلام

برای مورد اول، قبل از فهرست‌ها می‌تونید همچین کاری بکنید:

```tex
\renewcommand{\contentsname}{My nice list of contents}
\renewcommand{\listfigurename}{My nice list of figures}
\renewcommand{\listtablename}{My nice list of table}
```

برای مورد دوم، من پیشنهادم اینه که اصولاً توی فهرست‌ها مرجع عکس‌ها نیاد. برای این کار می‌تونید همچین کاری بکنید:
```tex
\caption[Short caption]{Long complete caption \cite{myref}}
```
این‌جوری توی فهرست کپشن کوتاه رو می‌نویسه، توی متن کپشن بلند به همراه مرجع رو. از لحاظ ویراستاری صحیح‌تره به نظرم.

اگه اصرار دارید رفرنس‌ها توی فهرست عکس‌ها هم بیاد باید سر حوصله روی کد تست کنم ببینم راهی پیدا می‌کنم یا نه. الان تو ذهنم نیست راهی.

**Comment by bexxnaz** [comment]
تغییرات رو برای فایل commands.txt اعمال کردم اما نام تصاویر و جداول  تغییری نکرد.
https://github.com/sinamomken/tehran-thesis/blob/79669850db960b307cc26d0e9cfb57236fa898af/tex/commands.tex#L191

ممنونم، لطف کردید.

**Comment by hadisfr** [comment]
من فکر کنم سؤالتون رو بد فهمیده بودم. اونی که گفتم، اگر داخل بخش document نوشته بشه، عنوان فهرست جداول و عنوان فهرست شکل‌ها رو عوض می‌کنه. اگر بخواید یه شکل یا جدول با نامی غیر از کپشنش توی فهرست‌ها بیاد باید از اون دستور دوم استفاده کنید که باعث می‌شه توی فهرست‌ها Short caption نوشته بشه برای اون تصویر یا جدول.

**Comment by bexxnaz** [comment]
سلام مجدد، بله متوجه شدم.
من منظورم همون دو خط کد بود که تو فایل commands.txt گذاشته بودم که تغییر نکرد. الان مشکلم حل شد. ممنونم. 
\renewcommand{\listfigurename}{My nice list of figures}
\renewcommand{\listtablename}{My nice list of table}
