### ISSUE TITLE
عدم نمایش مراجع

### ISSUE THREAD

**Issue by mmcheraghi** [sinamomken/tehran-thesis#34]
سلام. من همه با TexWorks کار می‌کنم. توزیع لاتک هم MikTex هستش. همه چیز درسته فقط مراجع رو چاپ نمی کنه و عوضش هرجا \cite نوشتم علامت سوال میگذاره. به نظرتون مشکل از کجاست؟

**Comment by hadisfr** [comment]
سلام
اصولاً لتک رو باید سه بار کامپایل کنید تا استیبل بشه. بار اول و در شرایطی بار دوم یه چیزهایی هنوز معلوم نیست و جاشون علامت سؤال میاد یا آپدیت نمی‌شه. سه بار کامپایل رو تست کردید؟

**Comment by mmcheraghi** [comment]
سلام خیلی ممنون. نفهمیدم چی شد اما الان برخی از مراجع رو آورده و مرجع جدید رو چاپ نمی کنه.

**Comment by hadisfr** [comment]
کلاً بعد از هر تغییر، سه بار دستور xelatex رو باید بزنید یا هر جور دیگه‌ای که کامپایل می‌کنید کامپایل کنید تا خروجی درست رو دریافت کنید. بار اول که کامپایل می‌کنید یه خروجی‌ای می‌گیرید ولی ممکنه ارجاعات و فهرست‌ها و… مشکلاتی داشته باشن.

**Comment by mmcheraghi** [comment]
خیلی ممنون
