### ISSUE TITLE
Have you ever had any issues with the xepersian package?

### ISSUE THREAD

**Issue by ghost** [sinamomken/tehran-thesis#5]
Hi

If you ever happen to have any question, then please open an issue at [the `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) and I will be very happy to help out.

Best wishes, Vafa Khalighi (the author of the `xepersian` package)

**Comment by hadisfr** [comment]
Current address of `xepersian` issue tracker is in https://github.com/vafa-ac/xepersian/issues. It may be moved to somewhere else over time.
