### ISSUE TITLE
عدم دسته بندی واژگان در بخش واژه نامه فارسی به انگلیسی

### ISSUE THREAD

**Issue by SaeedZhiany** [sinamomken/tehran-thesis#8]
<div dir="rtl" align="right">
با سلام

ضمن تشکر از این بسته‌ی خیلی خوب شما،
بنده مشکلی در بخش واژه نامه‌ی فارسی به انگلیسی دارم.
این واژه نامه بر اساس حروف الفبا دسته بندی نمی شوند و صرفا همه ی کلمات پشت سر هم در واژه نامه درج شده اند. لازم به ذکر است هیچ تنظیماتی را در فایل‌های مربوط دستکاری نکرده‌ام.

آیا باید دستور خاصی را برای اینکار به تنظیمات اضافه کنم؟ یا ترتیب خاصی در کامپایل ها داشته باشم؟
 (در ابتدا واژه نامه به طور کلی چاپ نمیشد. برای رفع این مشکل یک بار با xelatex، سپس با makeglossaries و سپس دو بار با xelatex کامپایل گرفته ام. واژه نامه ی انگلیسی درست رندر شده اما واژه نامه فارسی خیر.)

پیشاپیش ممنون از راهنمایی شما.
</div>

**Comment by hadisfr** [comment]
سلام
برای مرتب کردن واژه‌نامۀ فارسی استفاده از xindy رو‌ هم امتحان کنید. من با دستور makeglossaries کار نکرده‌ام، ولی ترکیب xindy با فلگ‌های مناسب زبان فارسی و makeindex سابقاً مشکل رو حل می‌کرد.
جزئیات دستورهای مورد نیاز رو داخل فایل build.sh می‌تونید پیدا کنید. اگر مشکل حل نشد بگین.
با آرزوی شادی!

**Comment by hadisfr** [comment]
‫با توجه به عدم دریافت پاسخ جدید، به نظر می‌رسه مشکل حل شده.
