### ISSUE TITLE
مشکل در اجرای استفاده از تمپلیت

### ISSUE THREAD

**Issue by KianNorouzi** [sinamomken/tehran-thesis#9]
سلام و ممنون بابت این تمپلیت مفید.
من هنگام اجرای کد دست نخورده شما با این پیام خطا مواجه میشم:

commands.tex
117
Undefined control sequence.
\__xepersian_mathsdigitspec_primitive_font_char_if_exist:nF ...
                                                  \l_fontspec_font "#1\scan_...
l.117 \setiranicfont
                    [Path={./font/}, Scale=1.3]{IRLotusICEE_Iranic.ttf}^^I^^...

تک لایو کامل و همینطور فونت های موجود در پوشه فونت رو نصب کردم
ممنون میشم اگر منو راهنمایی کنید که مشکل کجاست

**Comment by hadisfr** [comment]
‫سلام
‫حدس می‌زنم مشکل از نسخهٔ آخر بستهٔ xepersian باشه.
‫یا باید بستهٔ مذکور فیکس بشه (https://github.com/persiantex/xepersian/pull/19) یا از راه‌حل‌های موقت مثل اون‌چه که در https://github.com/persiantex/xepersian/issues/17 اومده استفاده کنید.
‫موفق باشید!

**Comment by hadisfr** [comment]
‫با توجه به عدم دریافت پاسخ جدید، به نظر می‌رسه مشکل حل شده.
